import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Gallery } from "@/components/Gallery";
import { SummaryActions } from "@/components/SummaryActions";
import { ThreeDChat } from "@/components/ThreeDChat";
import { ChatPanel } from "@/components/ChatPanel";
import { MortgageCalculator } from "@/components/MortgageCalculator";
import { PropertyMap } from "@/components/PropertyMap";
import { PropertyCard } from "@/components/PropertyCard";
import { formatPrice, getProperty, apiFetch } from "@/lib/api";
import type { PropertyDetail, PropertySummary } from "@/lib/types";

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{try{const{slug}=await params;const p=await getProperty(slug);const image=p.media[0]?.url;return{title:p.title,description:p.description.slice(0,160),alternates:{canonical:`/properties/${p.slug}`},openGraph:{title:p.title,description:p.description.slice(0,160),images:image?[{url:image}]:[]}}}catch{return{title:"Không tìm thấy bất động sản"}}}

export default async function PropertyPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;let property:PropertyDetail;try{property=await getProperty(slug)}catch{notFound()}
  let similar:PropertySummary[]=[];try{similar=await apiFetch<PropertyDetail[]>(`/properties/${property.slug}/similar?limit=3`)}catch{}
  const schema={"@context":"https://schema.org","@type":property.property_type==="apartment"?"Apartment":"SingleFamilyResidence",name:property.title,description:property.description,url:`${process.env.NEXT_PUBLIC_SITE_URL||'http://localhost:3000'}/properties/${property.slug}`,image:property.media.map((x)=>x.url),address:{"@type":"PostalAddress",streetAddress:property.address,addressLocality:property.district,addressRegion:property.city,addressCountry:"VN"},floorSize:{"@type":"QuantitativeValue",value:property.area_m2,unitCode:"MTK"},numberOfBedrooms:property.bedrooms,numberOfBathroomsTotal:property.bathrooms,offers:{"@type":"Offer",price:property.price,priceCurrency:property.currency,availability:"https://schema.org/InStock"}};
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="section-tight"><div className="container stack" style={{gap:26}}><div className="muted" style={{fontSize:'.88rem'}}>Trang chủ / {property.city} / {property.district} / {property.title}</div><div className="detail-hero"><div><Gallery media={property.media} title={property.title}/></div><aside className="card summary-card"><div className="stack" style={{gap:8}}><span className="row-wrap">{property.is_verified&&<span className="badge badge-brand">✓ Đã xác minh</span>}{property.has_3d&&<span className="badge badge-brand">◉ Có tour 3D</span>}</span><div className="summary-price">{formatPrice(property.price,property.transaction_type)}</div><h1 style={{fontSize:'2rem'}}>{property.title}</h1><p className="muted">{property.address}, {property.district}, {property.city}</p></div><div className="detail-stats"><div className="stat"><strong>{property.area_m2}</strong><div className="muted">m²</div></div><div className="stat"><strong>{property.bedrooms}</strong><div className="muted">Phòng ngủ</div></div><div className="stat"><strong>{property.bathrooms}</strong><div className="muted">WC</div></div></div><div className="stack" style={{gap:8}}><div className="row" style={{justifyContent:'space-between'}}><span className="muted">Pháp lý</span><strong>{property.legal_status||'Chưa cập nhật'}</strong></div><div className="row" style={{justifyContent:'space-between'}}><span className="muted">Nội thất</span><strong>{property.furnishing||'Chưa cập nhật'}</strong></div><div className="row" style={{justifyContent:'space-between'}}><span className="muted">Cập nhật</span><strong>{new Date(property.updated_at).toLocaleDateString('vi-VN')}</strong></div></div><SummaryActions propertyId={property.id} phone={property.agent?.phone}/>{property.agent&&<div className="card card-padded stack"><div className="row" style={{justifyContent:'space-between'}}><strong>{property.agent.display_name}</strong>{property.agent.verified&&<span className="badge badge-brand">Đã xác minh</span>}</div><p className="muted">{property.agent.agency?.name} · ⭐ {property.agent.rating}</p></div>}</aside></div>
      <nav className="tabs"><a className="tab-link" href="#overview">Tổng quan</a>{property.model_3d&&<a className="tab-link" href="#viewer">Tour 3D</a>}<a className="tab-link" href="#amenities">Tiện ích</a><a className="tab-link" href="#location">Vị trí</a><a className="tab-link" href="#legal">Pháp lý</a><a className="tab-link" href="#mortgage">Khoản vay</a></nav>
      <div className="detail-content" id="overview"><div className="stack" style={{gap:28}}><section className="stack"><span className="eyebrow">Tổng quan</span><h2>Không gian sống và thông tin căn nhà</h2><p className="muted" style={{fontSize:'1.05rem'}}>{property.description}</p></section><section className="card card-padded grid grid-3">{[['Loại hình',property.property_type],['Số tầng',String(property.floors_count)],['Chỗ đỗ xe',String(property.parking_spaces)],['Năm xây dựng',String(property.year_built||'—')],['Hướng',property.direction||'—'],['Tin chính chủ',property.is_owner_listing?'Có':'Không']].map(([k,v])=><div key={k}><div className="muted">{k}</div><strong>{v}</strong></div>)}</section><section className="stack" id="amenities"><h2>Tiện ích nổi bật</h2><div className="row-wrap">{property.features.map((x)=><span key={x.id} className="badge badge-brand">✓ {x.name}</span>)}</div></section><MortgageCalculator price={property.price}/></div><ChatPanel propertyId={property.id}/></div>
      {property.model_3d&&<section id="viewer" className="section-tight stack"><div><span className="eyebrow">Interactive tour</span><h2>Khám phá mô hình 3D và hỏi AI theo từng phòng</h2></div><ThreeDChat model={property.model_3d} propertyId={property.id}/></section>}
      <section className="section-tight grid grid-2" id="location"><div className="stack"><span className="eyebrow">Vị trí</span><h2>Tiện ích xung quanh</h2>{property.nearby_places.map((x)=><div className="card card-padded row" key={x.id} style={{justifyContent:'space-between'}}><div><strong>{x.name}</strong><div className="muted">{x.category}</div></div><span>{x.distance_m} m</span></div>)}</div><PropertyMap properties={[property]}/></section>
      <section className="section-tight stack" id="legal"><span className="eyebrow">Tài liệu</span><h2>Pháp lý và hồ sơ</h2>{property.documents.length?<div className="grid grid-3">{property.documents.map((d)=><a className="card card-padded stack" href={d.url} key={d.id} target="_blank"><strong>{d.title}</strong><span className={`badge ${d.verified?'badge-brand':'badge-warning'}`}>{d.verified?'Đã xác minh':'Chưa xác minh'}</span></a>)}</div>:<div className="empty">Chưa có tài liệu công khai.</div>}</section>
      {similar.length>0&&<section className="section-tight stack"><div><span className="eyebrow">Có thể phù hợp</span><h2>Bất động sản tương tự</h2></div><div className="property-grid">{similar.map((p)=><PropertyCard property={p} key={p.id}/>)}</div></section>}
    </div></section></>;
}
