"use client";
import { Canvas, useLoader, useThree } from "@react-three/fiber";
import { OrbitControls, Html } from "@react-three/drei";
import { TextureLoader, BackSide, Vector3, PerspectiveCamera } from "three";
import { Suspense, useEffect, useState } from "react";
import { clientApi } from "@/lib/client-api";
import { track } from "@/lib/analytics";

type Scene={id:string;name:string;image_url:string;thumbnail_url?:string;initial_yaw:number;initial_pitch:number;initial_fov:number;floor_id?:string|null};
type Link={id:string;source_scene_id:string;target_scene_id:string;yaw:number;pitch:number;label?:string};
type Hotspot={id:string;scene_id:string;yaw:number;pitch:number;label:string;description?:string};
type Graph={scenes:Scene[];links:Link[];hotspots:Hotspot[];navigation_zones:any[]};
function pos(yaw:number,pitch:number,r=8){const phi=(90-pitch)*Math.PI/180;const theta=(yaw+180)*Math.PI/180;return new Vector3(-r*Math.sin(phi)*Math.cos(theta),r*Math.cos(phi),r*Math.sin(phi)*Math.sin(theta));}
function Sphere({scene,links,hotspots,onScene}:{scene:Scene;links:Link[];hotspots:Hotspot[];onScene:(id:string)=>void}){const texture=useLoader(TextureLoader,scene.image_url);const{camera}=useThree();useEffect(()=>{if(camera instanceof PerspectiveCamera){camera.fov=scene.initial_fov||75;camera.updateProjectionMatrix();}},[camera,scene]);return <><mesh scale={[-1,1,1]}><sphereGeometry args={[10,64,40]}/><meshBasicMaterial map={texture} side={BackSide}/></mesh>{links.map(link=><Html key={link.id} position={pos(link.yaw,link.pitch)} center><button className="btn btn-primary btn-sm" onClick={()=>onScene(link.target_scene_id)}>↗ {link.label||"Sang phòng"}</button></Html>)}{hotspots.map(h=><Html key={h.id} position={pos(h.yaw,h.pitch,7.8)} center><div className="badge badge-brand" title={h.description}>● {h.label}</div></Html>)}</>}
export function PanoramaViewer({propertyId}:{propertyId:string}){const[graph,setGraph]=useState<Graph|null>(null);const[current,setCurrent]=useState<string|null>(null);useEffect(()=>{clientApi<Graph>(`/properties/${propertyId}/panorama`).then(g=>{setGraph(g);setCurrent(g.scenes[0]?.id||null)}).catch(()=>setGraph({scenes:[],links:[],hotspots:[],navigation_zones:[]}));},[propertyId]);const scene=graph?.scenes.find(x=>x.id===current);const links=graph?.links.filter(x=>x.source_scene_id===current)||[];const hotspots=graph?.hotspots.filter(x=>x.scene_id===current)||[];if(!graph)return <div className="viewer-loading">Đang tải panorama…</div>;if(!scene)return <div className="empty">Chưa có panorama 360° cho căn nhà này.</div>;return <div className="stack"><div className="viewer-shell" style={{height:520}}><Canvas camera={{position:[0,0,.1],fov:scene.initial_fov||75}}><Suspense fallback={<Html center><div className="badge">Đang tải ảnh 360°…</div></Html>}><Sphere scene={scene} links={links} hotspots={hotspots} onScene={(id)=>{setCurrent(id);track("panorama_started",{sceneId:id},propertyId)}}/></Suspense><OrbitControls enableZoom enablePan={false} rotateSpeed={-0.25}/></Canvas></div><div className="row-wrap">{graph.scenes.map(s=><button key={s.id} className={`btn btn-sm ${s.id===current?"btn-primary":"btn-secondary"}`} onClick={()=>{setCurrent(s.id);track("panorama_started",{sceneId:s.id},propertyId)}}>{s.name}</button>)}</div><div className="card card-padded"><strong>Mini-map / vùng di chuyển</strong><div className="muted">{graph.navigation_zones.length} vùng navigation đã cấu hình. Hotspot và tầng được đồng bộ theo scene.</div></div></div>}
