"use client";
import { FormEvent, useState } from "react";

export function AppointmentForm({propertyId,open,onClose}:{propertyId:string;open:boolean;onClose:()=>void}){
  const [status,setStatus]=useState<"idle"|"loading"|"success"|"error">("idle"); const [message,setMessage]=useState("");
  if(!open)return null;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus("loading");const form=new FormData(event.currentTarget);const scheduledLocal=String(form.get("scheduled_at"));const payload={property_id:propertyId,full_name:form.get("full_name"),phone:form.get("phone"),email:form.get("email")||null,scheduled_at:new Date(scheduledLocal).toISOString(),note:form.get("note")||null};const response=await fetch("/api/backend/appointments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(response.ok){setStatus("success");setMessage("Lịch xem đã được ghi nhận. Tư vấn viên sẽ xác nhận sớm.");}else{setStatus("error");setMessage((await response.json()).detail||"Không thể tạo lịch hẹn.");}}
  const min=new Date(Date.now()+3600_000).toISOString().slice(0,16);
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Đặt lịch xem nhà"><div className="modal stack"><div className="row" style={{justifyContent:"space-between"}}><h2 style={{fontSize:"1.7rem"}}>Đặt lịch xem nhà</h2><button className="btn btn-ghost" type="button" onClick={onClose}>✕</button></div>{status==="success"?<div className="alert success">{message}</div>:<form className="stack" onSubmit={submit}><label className="label">Họ và tên<input required className="input" name="full_name"/></label><div className="grid grid-2"><label className="label">Số điện thoại<input required className="input" name="phone" inputMode="tel"/></label><label className="label">Email<input className="input" name="email" type="email"/></label></div><label className="label">Thời gian mong muốn<input required className="input" name="scheduled_at" type="datetime-local" min={min}/></label><label className="label">Ghi chú<textarea className="textarea" name="note"/></label>{status==="error"&&<div className="alert">{message}</div>}<button className="btn btn-primary" disabled={status==="loading"}>{status==="loading"?"Đang gửi…":"Xác nhận lịch xem"}</button></form>}<p className="muted" style={{fontSize:'.85rem'}}>Thông tin liên hệ chỉ được dùng để xác nhận lịch hẹn và không được chia sẻ cho nhà quảng cáo.</p></div></div>;
}
