"use client";
import { useState } from "react";
import { useSearchParams } from "next/navigation";

const propertyTypes = [{v:"apartment",l:"Căn hộ"},{v:"townhouse",l:"Nhà phố"},{v:"villa",l:"Biệt thự"},{v:"shophouse",l:"Shophouse"},{v:"land",l:"Đất"}];
export function SearchFilters({ districts }: { districts: string[] }) {
  const params = useSearchParams(); const [open, setOpen] = useState(false);
  return <><button className="btn btn-secondary mobile-menu" type="button" onClick={()=>setOpen(!open)}>{open ? "Đóng bộ lọc" : "Mở bộ lọc"}</button><form className={`filter-panel ${open ? "open" : ""}`} action="/properties" method="get"><label className="label">Từ khóa<input className="input" name="q" defaultValue={params.get("q") || params.get("natural_query") || ""} placeholder="Tên, địa chỉ…" /></label><label className="label">Nhu cầu<select className="select" name="transaction_type" defaultValue={params.get("transaction_type") || ""}><option value="">Tất cả</option><option value="sale">Mua</option><option value="rent">Thuê</option></select></label><label className="label">Loại bất động sản<select className="select" name="property_type" defaultValue={params.get("property_type") || ""}><option value="">Tất cả</option>{propertyTypes.map((x)=><option value={x.v} key={x.v}>{x.l}</option>)}</select></label><label className="label">Quận/huyện<select className="select" name="district" defaultValue={params.get("district") || ""}><option value="">Toàn Hà Nội</option>{districts.map((x)=><option key={x}>{x}</option>)}</select></label><div className="grid grid-2"><label className="label">Giá từ<input className="input" type="number" name="min_price" defaultValue={params.get("min_price") || ""} placeholder="VND" /></label><label className="label">Đến<input className="input" type="number" name="max_price" defaultValue={params.get("max_price") || ""} placeholder="VND" /></label></div><div className="grid grid-2"><label className="label">Diện tích từ<input className="input" type="number" name="min_area" defaultValue={params.get("min_area") || ""} /></label><label className="label">Phòng ngủ<input className="input" type="number" name="bedrooms" defaultValue={params.get("bedrooms") || ""} /></label></div><label className="row"><input type="checkbox" name="has_3d" value="true" defaultChecked={params.get("has_3d") === "true"}/> Chỉ hiện căn có 3D</label><label className="row"><input type="checkbox" name="is_owner_listing" value="true" defaultChecked={params.get("is_owner_listing") === "true"}/> Tin chính chủ</label><button className="btn btn-primary" type="submit">Áp dụng bộ lọc</button><a className="btn btn-secondary" href="/properties">Xóa bộ lọc</a></form></>;
}
